### ISSUE TITLE
Create bitswap Network for Testing

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs-bitswap#8]
Fire N number of nodes and connect all of them together

**Comment by dignifiedquire** [comment]
Pasting the notes from the etherpad. Later we should do also the same tests on full js-ipfs nodes, so that we account for every possibility

**bitswap tests**
- [ ] script to spawn a node, given a config file, creates a random file every X seconds and prints the hash (so that it can be requested
- spawn 1 node on the main thread with TCP
- dial to the other down
- fetch all of the blocks the other node outputs
- [ ] spawn 5 nodes in separate process and repeat the above
- [ ] spawn 10 nodes and ..
- [ ] spawn 20 nodes
- repeat the previous proc
- note: measure time (avg, max and min) of fetching the block and memory usage in the beginning and end

timing data in different events
  - use logs (debug)

**Comment by dignifiedquire** [comment]
In #17 there was a set of tests added that are skipped currently as we are seeing issues on CI with these. Need to figure out what's wrong and fix them.

**Comment by dignifiedquire** [comment]
I have enabled them in #25, lets see if we can get them to pass.

**Comment by dignifiedquire** [comment]
They run on CI now, only for 2 nodes, but it is something 😄
